# Generated by Django 2.1.8 on 2019-11-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20191109_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
